# 配置文件

DAILY_TIME: "14:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2018-02-03" # 纪念日
CITY: "贵州"

BIRTHDAY:
  - "08-04"

APP_ID: "粥粥专属的"
APP_SECRET: "粥粥专属的"

USER_ID: 
  - "微信公众平台的 USER ID"
  - "USER ID 2" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "微信公众平台的 TEMPLATE ID"
